# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема конференції')),
                ('slug', models.SlugField(blank=True)),
                ('level', models.CharField(max_length=70, verbose_name='Рівень конференції')),
                ('date', models.DateField(verbose_name='Дата конференції')),
                ('status', models.BooleanField(default=False, verbose_name='Статус конференції (проведена/непроведена)')),
                ('information_message', models.FileField(blank=True, upload_to='inform_messages/%Y/%m/%d', verbose_name='Інформаційне повідомлення')),
            ],
            options={
                'verbose_name': 'Конференція',
                'verbose_name_plural': 'Конференції',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference', verbose_name='Конференція')),
            ],
            options={
                'verbose_name': 'Учасник',
                'verbose_name_plural': 'Учасники',
                'ordering': ('participant_profile',),
            },
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('firstname', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('middlename', models.CharField(max_length=30, verbose_name='По-батькові')),
                ('academic_status', models.CharField(blank=True, choices=[('Доц.', 'Доцент'), ('Проф.', 'Професор'), ('Ст. наук. співробітник', 'Старший науковий співробітник')], default=None, max_length=30, null=True, verbose_name='Вчене звання')),
                ('degree', models.CharField(blank=True, choices=[('к.н.', 'кандидат наук'), ('д.н.', 'доктор наук'), ('Ph.D', 'доктор філософії')], default=None, max_length=30, null=True, verbose_name='Вчений ступінь')),
                ('job_position', models.CharField(max_length=70, verbose_name='Посада')),
                ('organisation', models.CharField(max_length=90, verbose_name='Організація')),
                ('country', models.CharField(max_length=50, verbose_name='Країна')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('address', models.CharField(max_length=100, verbose_name='Адреса')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('filling_date', models.DateField(auto_now_add=True, verbose_name='Дата заповнення')),
            ],
            options={
                'verbose_name': 'Профіль учасника',
                'verbose_name_plural': 'Профілі учасників',
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва доповіді')),
                ('section', models.CharField(choices=[('Природничі науки', 'Природничі науки'), ('Інформаційні технології', 'Інформаційні технології'), ('Механічна інженерія', 'Механічна інженерія'), ('Електрична інженерія', 'Електрична інженерія'), ('Автоматизація та приладобудування', 'Автоматизація та приладобудування'), ('Хімічна та біоінженерія', 'Хімічна та біоінженерія'), ('Електроніка та телекомунікації', 'Електроніка та телекомунікації'), ('Виробництво та технології', 'Виробництво та технології'), ('Архітектура та будівництво', 'Архітектура та будівництво'), ('Цивільна безпека', 'Цивільна безпека'), ('Транспорт', 'Транспорт')], max_length=35, verbose_name='Назва секції')),
                ('thesis', models.FileField(upload_to='theses/', verbose_name='Файл доповіді')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference', verbose_name='Конференція')),
            ],
            options={
                'verbose_name': 'Доповідь',
                'verbose_name_plural': 'Доповіді',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.ParticipantProfile', verbose_name='Профіль учасника'),
        ),
        migrations.AddField(
            model_name='author',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Participant', verbose_name='Учасник конференції'),
        ),
        migrations.AddField(
            model_name='author',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Thesis'),
        ),
    ]
