# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='title_eng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема конференції_англ.'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
