# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20180712_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='place',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Місце проведення'),
        ),
    ]
