# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20180724_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секція', 'verbose_name_plural': 'Секції'},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('title', 'participant')]),
        ),
    ]
