# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_conference_place'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantprofile',
            unique_together=set([('lastname', 'firstname', 'middlename')]),
        ),
    ]
