# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_auto_20180722_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ('-date_start',), 'verbose_name': 'Конференція', 'verbose_name_plural': 'Конференції'},
        ),
        migrations.RemoveField(
            model_name='conference',
            name='date',
        ),
        migrations.AddField(
            model_name='conference',
            name='date_end',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата завершення конференції'),
        ),
        migrations.AddField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата початку конференції'),
        ),
    ]
