# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_auto_20180729_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='middlename',
            field=models.CharField(default='--', max_length=30, verbose_name='По-батькові'),
        ),
    ]
