# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_auto_20180729_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, choices=[('к.н.', 'кандидат наук'), ('д.н.', 'доктор наук'), ('Ph.D', 'доктор філософії')], default=None, max_length=30, null=True, verbose_name='Науковий ступінь'),
        ),
    ]
