# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0010_auto_20180729_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='thesis_file',
            field=models.FileField(blank=True, null=True, upload_to='theses/%Y/%m/%d', verbose_name='Збірка доповідей'),
        ),
    ]
