# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 16:52
from __future__ import unicode_literals

import conferences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0011_auto_20180729_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='thesis_file',
            field=models.FileField(blank=True, null=True, upload_to='theses/%Y-%m-%d', verbose_name='Збірка доповідей'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='thesis',
            field=models.FileField(upload_to=conferences.models.get_upload_path, verbose_name='Файл доповіді'),
        ),
    ]
