# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0013_auto_20180729_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesis',
            options={'ordering': ('title', 'section'), 'verbose_name': 'Доповідь', 'verbose_name_plural': 'Доповіді'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('lastname', 'firstname'), 'verbose_name': 'Профіль учасника', 'verbose_name_plural': 'Профілі учасників'},
        ),
    ]
