# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0014_auto_20180802_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='thesis_file',
            new_name='thesises_file',
        ),
    ]
