# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0017_auto_20180824_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковий номер'),
        ),
    ]
