# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 16:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('annotation', models.CharField(help_text='Макс. 300 символів', max_length=300, verbose_name='Короткий зміст')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Зміст')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Новини',
                'verbose_name_plural': 'Новини',
                'ordering': ('-date_created',),
            },
        ),
    ]
