# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_news', '0002_auto_20180803_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='annotation',
            field=models.TextField(help_text='Макс. 300 символів', max_length=300, verbose_name='Короткий зміст'),
        ),
    ]
