# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'Контактна інформація',
                'verbose_name_plural': 'Контактна інформація',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='main_app.Contact', verbose_name='Електронні адреси')),
            ],
            options={
                'verbose_name': 'Електронна пошта',
                'verbose_name_plural': 'Електронні адреси',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ImageField(blank=True, null=True, upload_to='contacts/', verbose_name='Логотип оператора')),
                ('number', models.CharField(max_length=13, verbose_name='Номер телефону')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='main_app.Contact', verbose_name='Номери телефонів')),
            ],
            options={
                'verbose_name': 'Номер телефону',
                'verbose_name_plural': 'Номери телефонів',
            },
        ),
    ]
