# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=50)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('IP_location', models.CharField(blank=True, default='Unknown', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Пошуковий запит',
                'verbose_name_plural': 'Пошукові запити',
                'ordering': ('search_date',),
            },
        ),
    ]
