# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 16:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Учасник команди')),
            ],
            options={
                'verbose_name': 'Учасник',
                'verbose_name_plural': 'Учасники',
            },
        ),
        migrations.CreateModel(
            name='RoboSprintInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Короткий опис проекту')),
                ('title_image', models.ImageField(upload_to='images', verbose_name='Титульний рисунок')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Про проект')),
            ],
            options={
                'verbose_name': 'Про проект',
                'verbose_name_plural': 'Про проект',
            },
        ),
        migrations.CreateModel(
            name='RoboSprintProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Навчальна платформа')),
                ('model_requirements', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Вимоги до моделі')),
                ('route_requirements', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Вимоги до траси')),
                ('consulting', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Консультації')),
                ('robocar_file', models.FileField(upload_to='files', verbose_name='Бібліотека функцій керування')),
                ('driver', models.FileField(upload_to='files', verbose_name='Драйвер')),
            ],
            options={
                'verbose_name': 'Детальний опис',
                'verbose_name_plural': 'Детальний опис',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='teams', verbose_name='Логотип')),
                ('title', models.CharField(max_length=200, verbose_name='Назва команди')),
                ('school', models.CharField(max_length=250, verbose_name='Навчальний заклад')),
                ('city', models.CharField(max_length=100, verbose_name='Населений пункт')),
                ('leader_fullname', models.CharField(max_length=200, verbose_name="Прізвище, ім'я керівника")),
                ('leader_phone', models.CharField(max_length=15, verbose_name='Телефон керівника')),
                ('leader_email', models.EmailField(max_length=254, verbose_name='E-mail керівника')),
                ('captain', models.CharField(max_length=50, verbose_name='Капітан команди')),
                ('approved', models.BooleanField(default=False, verbose_name='Перевірено')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команди',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='robosprint.Team', verbose_name='Учасник'),
        ),
    ]
